standalone.directory=C:\\SEMOSS_v3.3.6.3_x64
semoss.home.directory=C:\\SEMOSS_v3.3.6.3_x64\\semosshome
monolith.directory=C:\\SEMOSS_v3.3.6.3_x64\\tomcat\\webapps\\Monolith
semoss.web.directory=C:\\SEMOSS_v3.3.6.3_x64\\tomcat\\webapps\\SemossWeb